import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Back to Home link in top left corner */}
        <div className="absolute left-0 top-0 m-4 z-50">
          <a href="/" className="text-indigo-700 font-semibold hover:underline bg-white/80 px-3 py-1 rounded shadow">
            &larr; Back to Home
          </a>
        </div>
        {/* Top Navigation/Header */}
        <header className="border-b bg-white/80 backdrop-blur supports-[backdrop-filter]:bg-white/60 sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex h-16 items-center justify-between">
              <a href="/" className="flex items-center gap-2 font-semibold text-indigo-700">
                <i className="fa-solid fa-graduation-cap"></i>
                <span>EduCounsel</span>
              </a>
              <button id="mobileMenuBtn" className="sm:hidden p-2 text-slate-600" aria-label="Open Menu">
                <i className="fa-solid fa-bars text-xl"></i>
              </button>
              <nav id="mainNav" className="hidden sm:flex gap-6">
                <a href="/" className="nav-link hover:text-indigo-700">Home</a>
                <a href="/school-education" className="nav-link hover:text-indigo-700">School Education</a>
                <a href="/counselling" className="nav-link hover:text-indigo-700">Child/Parent Counselling</a>
                <a href="/languages" className="nav-link hover:text-indigo-700">Languages</a>
                <a href="/about" className="nav-link hover:text-indigo-700">About Us</a>
                <a href="/contact" className="nav-link hover:text-indigo-700">Contact Us</a>
              </nav>
            </div>
            {/* Mobile menu (static, not functional in this snippet) */}
            <nav id="mobileNav" className="sm:hidden hidden pb-4">
              <ul className="flex flex-col gap-2">
                <li><a className="block px-2 py-2 rounded hover:bg-indigo-50" href="/">Home</a></li>
                <li><a className="block px-2 py-2 rounded hover:bg-indigo-50" href="/school-education">School Education</a></li>
                <li><a className="block px-2 py-2 rounded hover:bg-indigo-50" href="/counselling">Child/Parent Counselling</a></li>
                <li><a className="block px-2 py-2 rounded hover:bg-indigo-50" href="/languages">Languages</a></li>
                <li><a className="block px-2 py-2 rounded hover:bg-indigo-50" href="/about">About Us</a></li>
                <li><a className="block px-2 py-2 rounded hover:bg-indigo-50" href="/contact">Contact Us</a></li>
              </ul>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
